# BASE
base:
  random_state: 42
  test_size: 0.2
  root_project_dir: /mnt/c/Jupyter-projects/mag_ML

# DATA
data:
  raw_dataset_csv: data/raw/insurance.csv

  processed_dataset_csv: data/processed/insurance_processed.csv
  dataset_x_path_np: data/processed/data_x.npy
  dataset_y_path_np: data/processed/data_y.npy

  train_path: data/processed/train.csv
  test_path: data/processed/test.csv
  target_column: charges

# REPORTS
reports:
  ydata_report_path: reports/ydata_report.html
  dvclive_path: dvclive/
  metrics_path: reports/metrics/
  figures_path: reports/figures/

# MODELS  
models:
  models_path: models/

  linear:
    n_jobs:

  decision_tree:
    criterion: squared_error
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 3
    random_state: 42

  xgboost:
    n_estimators: 200
    learning_rate: 0.05
    max_depth: 10
    subsample: 0.8
    colsample_bytree: 0.75
    random_state: 42

  catboost:
    iterations: 300
    depth: 4
    learning_rate: 0.05
    loss_function: RMSE
    verbose: false
    random_seed: 42

  ann:
    dataset_params:
      validation_split: 0.2
      batch_size: 16
      random_state: 42
    model_params:
      n_hidden_layers: 2
      n_neurons: 8
      activation: 'tanh'
      learning_rate: 0.001
    train_params:
      epochs: 100
      verbose: 0